version: "3.8"

services:
  backend:
    build: .
    container_name: gallery-backend
    ports:
      - "7000:7000"
    env_file:
      - ./config/.local.env
    depends_on:
      - mongo
    command: ["node", "app.js"]

  mongo:
    image: mongo:6
    container_name: gallery-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
